### ISSUE TITLE
SSH login as "user” : user@xx.xx.xx.xx: Permission denied (publickey, password) (running the AVP demo on Local Hardware)

### ISSUE THREAD

**Issue by ota-ri** [DensoSVIC/soafee-avp-blueprint#16]
We trialled running the AVP demo on Local Hardware.
The following error occurs in `blueprint init-user` command.

![Image](https://github.com/user-attachments/assets/e4491223-29c3-4071-8bbf-2c99008f8626)

In our environments, 
onsite-avp-ewoal's host have "ubuntu" user instead of "user" user.

What is the correct way to handle this issue?
If the following workaround is correct, could you add this method to the procedure?

Workaround:
Add `ansible_user` configuration in `configure.yaml`

```
avp_ewaol:
  hosts:
   onsite-avp-ewaol:
     ansible_ssh_host: "10.91.83.211"
     ansible_user: "ubuntu"       # Add configuration 
     cloud_instance: false
```
