### ISSUE TITLE
xhost: unable open display. Authorization required, but no authorization protocol specified. (running the AVP demo on Local Hardware)

### ISSUE THREAD

**Issue by ota-ri** [DensoSVIC/soafee-avp-blueprint#24]
We trialled running the AVP demo on Local Hardware.
The following error occurs in `blueprint configure` command.

![Image](https://github.com/user-attachments/assets/8ce8df43-ea73-4abb-b8d4-ff4c3647661e)

What is the correct way to handle this issue?
Is it possible to define it as a variable rather than a fixed value?
(the following workaround is procedure by a fixed value)

Workaround:
Configure the value of the confirmed DISPLAY variable
```
- name: Set fact display
  ansible.builtin.set_fact:
  #display: "{{ _dcv_display.stdout | default(ansible_env.DISPLAY) | default(':0') }}"
  display: "{{ _dcv_display.stdout | default(ansible_env.DISPLAY) | default(':1') }}"
```
