### ISSUE TITLE
Complex steps to revise playbook when running the AVP Demo on Local Hardware

### ISSUE THREAD

**Issue by ota-ri** [DensoSVIC/soafee-avp-blueprint#28]
When trialing to run the AVP Demo on Local Hardware, we found the playbook revision procedure difficult.

> If you plan to use a single hardware instance for more than one role, such as running Xronos Dashboard and the AVP render on the same host, define the host only once in the inventory and then include it as a child of any additional roles.

I would appreciate it if you could describe how to modify it in detail in the procedure.

Workaround:
In our envrionmets,
- Laptop PC(amd64): for running Render and Dashboard(avp-render, xronos-dashbord)
- NVIDIA Jetson Orin AGX(arm64): for running compute(avp-ewaol, avp-render)

Revised with the following policy:
- Basically replace the hosts as follows:
  - avp_ewaol, avp_builder → avp_ewaol
  - avp_render, xronos_dashboard → avp_render
- Exceptions
  -  In the build task, use "avp_builder" instead of "avp_ewaol"
  -  hosts for Gather facts task does NOT revise

For example,
<details>
<summary>Revised avp.yml</summary>

```
# SPDX-FileCopyrightText: (c) 2025 Xronos Inc. Licensed to DENSO International America, Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Gather facts
  hosts: avp_render, avp_ewaol, avp_builder    # Do Not change
  tags: [never, clean, build]
  gather_facts: false
  tasks:
    - ansible.builtin.setup:


##################
#   stop
##################

- hosts: avp_render
  tags: [never, stop]
  gather_facts: false
  roles:
    - name: stop
      role: stop
      vars:
        avp_close_firefox_on_stop: true


##################
#   clean
##################

#- hosts: avp_render, avp_ewaol, avp_builder
- hosts: avp_render, avp_ewaol                                        # Revise: avp_ewaol, avp_builder → avp_ewaol
  tags: [never, clean]
  gather_facts: false
  ignore_errors: true
  roles:
    - name: clean
      role: clean


##################
#   build
##################

#- hosts: avp_builder, avp_render, avp_ewaol
- hosts: avp_builder, avp_render                                     # Leave avp_builder instead of avp_ewaol
  tags: [never, build]
  gather_facts: false
  tasks:
    - name: Docker login to container registry
      ansible.builtin.import_tasks: tasks/ecr-docker-login.yml

- hosts: avp_render
  tags: [never, build]
  gather_facts: false
  tasks:
    - name: k3s authenticate with container registry
      ansible.builtin.import_tasks: tasks/ecr-k3s-login.yml

#- hosts: avp_render, avp_builder, avp_ewaol
- hosts: avp_render, avp_builder                                     # Leave avp_builder instead of avp_ewaol
  tags: [never, build]
  gather_facts: false
  tasks:
    - name: Git clone soafee-avp-demo version {{ soafee_avp_demo_version }}
      ansible.builtin.git:
        repo: "{{ soafee_avp_demo_repo_uri }}"
        version: "{{ soafee_avp_demo_version }}"
        accept_newhostkey: true
        dest: "{{ soafee_avp_demo_path }}"
        force: true

- hosts: avp_builder, avp_render
  tags: [never, build]
  gather_facts: false
  roles:
    - name: build_openadkit
      role: build_openadkit

    - name: build_lingua_franca
      role: build_lingua_franca

- hosts: avp_render, avp_ewaol
  tags: [never, build]
  gather_facts: false
  roles:
    - name: pull_openadkit
      role: pull_openadkit

- hosts: avp_builder
  tags: [never, build]
  gather_facts: false
  roles:
    - name: build_federate_images
      role: build_federate_images

- hosts: avp_render
  tags: [never, build]
  gather_facts: false
  roles:
    - name: build_render_images
      role: build_render_images

    - name: build_k3s_manifests
      role: build_k3s_manifests
      vars:
        _k3s_use_gpu: false

- hosts: avp_ewaol
  tags: [never, build]
  gather_facts: false
  roles:
    - name: pull_federate_images
      role: pull_federate_images

- hosts: avp_render
  tags: [never, build]
  gather_facts: false
  tasks:
    - name: k3s apply deployment
      kubernetes.core.k8s:
        state: present
        apply: true
        force: true
        src: "{{ soafee_dir }}/k3s/k3s-combined-resources.yml"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        namespace: "{{ deployment }}-{{ ansible_user }}"
        wait: true
        wait_timeout: 360


##################
#   start
##################

- hosts: avp_render
  tags: [never, start]
  gather_facts: false
  roles:
    - name: start
      role: start

``` 
</details>

`configure-adduser.yml` and `configure.yml` as well.
